### ISSUE TITLE
User Auth Checklist

### ISSUE THREAD

**Issue by steventran91** [steventran91/Faybuk#2]
# User Auth
## Functionality
- [x] Has working demo login
- [x] Smooth, bug free navigation
### Before Login
- [x] The `/login` page should not display a link to `Log In`. Same for `/signup`
- [x] Going to a random route `/#/oweiniouewbrviuwebv` should redirect or display a 404 page
- [x] Errors should display for both `/signup` and `/login`.
- [x] Errors should clear when moving between `/signup` and `/login`.
- [x] Can sign up a user
- [x] Can sign in as a user
- [x] Can log out a user
- [x] Can't sign up with the same username/email
- [x] Pressing enter after filling out the session form should use the form data, not the demo user
### After Login
- [x] Should not be able to visit `/login` or `/signup`
- [x] Should be able to refresh the page and still be logged in
## Style
- [x] Things should be positioned correctly.
- [x] All relevant elements should have `cursor: pointer` on hover
- [x] Remove Redux logger and all console.log()'s from production
## Seeds
- [x] Adequate and appropriate seeds

**Comment by samwalker191** [comment]
I think I broke something when trying to sign up. 

One thing I did notice before it broke, the demo login wasnt working. I think due to not having the production db seeded with a demo user.

**Comment by steventran91** [comment]
I just seeded the demo user to heroku. I checked my app on heroku and was able to login as demo user successfully.

**Comment by samwalker191** [comment]
Dope, yea its working for me now.

- [x] the errors for the sign up form show up on the login form in the background. 
- [x] make sure to do some styling over the weekend

**Comment by steventran91** [comment]
Hey Walker, fixed the issue regarding errors and added styling to my sign up modal.
